"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Sparkles, Loader2, Info, ShieldAlert } from "lucide-react";
import { SectionCard } from "@/components/patterns/section-card";
import { StatusBadge } from "@/components/patterns/status-badge";
import { requestAiAudit } from "@/lib/persistence/ai-audit-actions";
import type { AiAuditState } from "@/lib/ai/run-audit";

/**
 * The AI explanation layer.
 *
 * Structurally incapable of hiding the deterministic report: it renders as its
 * own section BELOW the integrity metrics, fetches after mount, and every
 * failure state degrades to a sentence. Nothing on this page waits for it.
 */

const RISK_TONE = { low: "success", medium: "warning", high: "destructive" } as const;

const UNAVAILABLE_MESSAGE =
  "AI review is unavailable. Your deterministic import integrity report is unaffected.";
const INVALID_MESSAGE = "AI review could not be validated. No imported data was changed.";
const ERROR_MESSAGE =
  "AI review could not be completed. Your deterministic import integrity report is unaffected.";

interface AiImportReviewProps {
  importRunId: string;
  /** Row ids that exist on this page, so a recommendation can link to them. */
  issueLinkBase: string;
}

export function AiImportReview({ importRunId, issueLinkBase }: AiImportReviewProps) {
  const [state, setState] = useState<AiAuditState | null>(null);

  useEffect(() => {
    let active = true;
    requestAiAudit(importRunId)
      .then((result) => {
        if (active) setState(result);
      })
      .catch(() => {
        // A Server Action that rejects must not leave this stuck on a spinner.
        if (active) setState({ status: "error" });
      });
    return () => {
      active = false;
    };
  }, [importRunId]);

  return (
    <SectionCard
      title="AI Import Review"
      description="A plain-language explanation of the report above. Generated by a language model from the deterministic results only — it cannot change them, and it never sees your template's content."
    >
      {state === null ? <LoadingState /> : <ResolvedState state={state} issueLinkBase={issueLinkBase} />}
    </SectionCard>
  );
}

function LoadingState() {
  return (
    <div className="flex items-center gap-2 text-sm text-text-muted" aria-live="polite">
      <Loader2 className="size-4 animate-spin" aria-hidden="true" />
      Preparing a plain-language summary…
    </div>
  );
}

function Notice({ children, icon: Icon }: { children: string; icon: typeof Info }) {
  return (
    <p className="flex items-start gap-2 rounded-lg border border-border bg-surface-muted px-3 py-2 text-sm text-text-muted">
      <Icon className="mt-0.5 size-4 shrink-0" aria-hidden="true" />
      {children}
    </p>
  );
}

function ResolvedState({ state, issueLinkBase }: { state: AiAuditState; issueLinkBase: string }) {
  if (state.status === "unavailable") return <Notice icon={Info}>{UNAVAILABLE_MESSAGE}</Notice>;
  if (state.status === "invalid") return <Notice icon={ShieldAlert}>{INVALID_MESSAGE}</Notice>;
  if (state.status === "error") return <Notice icon={ShieldAlert}>{ERROR_MESSAGE}</Notice>;

  const { output } = state;

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap items-center gap-2">
        <span className="flex items-center gap-1.5 text-sm font-medium text-text">
          <Sparkles className="size-4 text-text-muted" aria-hidden="true" />
          Suggested attention level
        </span>
        <StatusBadge tone={RISK_TONE[output.riskLevel]}>{output.riskLevel}</StatusBadge>
        <span className="text-xs text-text-muted">advisory only — the status above is the authoritative result</span>
      </div>

      <p className="text-sm text-text">{output.summary}</p>

      <div>
        <h3 className="mb-1 text-sm font-semibold text-text">What to do next</h3>
        <p className="text-sm text-text-muted">{output.reviewMessage}</p>
      </div>

      {output.recommendedIssueIds.length > 0 ? (
        <div>
          <h3 className="mb-1 text-sm font-semibold text-text">
            Suggested issues to review ({output.recommendedIssueIds.length})
          </h3>
          <p className="mb-2 text-xs text-text-muted">
            Every id below was checked against the issues actually recorded for this import.
          </p>
          <div className="flex flex-wrap gap-2">
            {output.recommendedIssueIds.map((id, index) => (
              <Link
                key={id}
                href={issueLinkBase}
                className="rounded-md border border-border px-2 py-1 text-xs text-text outline-none transition-colors hover:bg-surface-muted focus-visible:ring-2 focus-visible:ring-ring/50"
              >
                Issue #{index + 1}
              </Link>
            ))}
          </div>
        </div>
      ) : null}

      {output.limitationsMentioned.length > 0 ? (
        <div>
          <h3 className="mb-1 text-sm font-semibold text-text">Limitations worth knowing</h3>
          <ul className="flex list-disc flex-col gap-1 pl-5 text-sm text-text-muted">
            {output.limitationsMentioned.map((limitation) => (
              <li key={limitation}>{limitation}</li>
            ))}
          </ul>
        </div>
      ) : null}

      <p className="text-xs text-text-muted">
        Generated by {state.model}. This explanation is not a source of truth — if it disagrees with the
        integrity report above, the integrity report is correct.
      </p>
    </div>
  );
}
